import { Book, FileText, BotMessageSquare } from 'lucide-react';
import type { Exam, Resource } from './types';

export const exams: Exam[] = [
  { id: 'jee', name: 'JEE (Main and Advanced)' },
  { id: 'neet', name: 'NEET' },
  { id: 'upsc', name: 'UPSC Civil Services' },
  { id: 'cat', name: 'CAT' },
  { id: 'gate', name: 'GATE' },
];

export const resources: Resource[] = [
  {
    title: 'Study Materials',
    description: 'Access curated notes and guides.',
    icon: Book,
    href: '#',
  },
  {
    title: 'Sample Papers',
    description: 'Practice with model question papers.',
    icon: FileText,
    href: '#',
  },
  {
    title: 'Previous Year Questions',
    description: 'Analyze past trends with PYQs.',
    icon: FileText,
    href: '#',
  },
  {
    title: 'AI Trainer',
    description: 'Get your doubts cleared instantly.',
    icon: BotMessageSquare,
    href: '/trainer',
  },
];

export const topics: Record<string, string[]> = {
    jee: [
        "Physics - Units and Measurements",
        "Physics - Kinematics",
        "Physics - Laws of Motion",
        "Physics - Work, Energy and Power",
        "Physics - Rotational Motion",
        "Physics - Gravitation",
        "Physics - Properties of Solids and Liquids",
        "Physics - Thermodynamics",
        "Physics - Kinetic Theory of Gases",
        "Physics - Oscillations and Waves",
        "Physics - Electrostatics",
        "Physics - Current Electricity",
        "Physics - Magnetic Effects of Current and Magnetism",
        "Physics - Electromagnetic Induction and Alternating Currents",
        "Physics - Electromagnetic Waves",
        "Physics - Optics",
        "Physics - Dual Nature of Matter and Radiation",
        "Physics - Atoms and Nuclei",
        "Physics - Electronic Devices",
        "Chemistry - Some Basic Concepts in Chemistry",
        "Chemistry - States of Matter",
        "Chemistry - Atomic Structure",
        "Chemistry - Chemical Bonding and Molecular Structure",
        "Chemistry - Chemical Thermodynamics",
        "Chemistry - Solutions",
        "Chemistry - Equilibrium",
        "Chemistry - Redox Reactions and Electrochemistry",
        "Chemistry - Chemical Kinetics",
        "Chemistry - Surface Chemistry",
        "Chemistry - Classification of Elements and Periodicity in Properties",
        "Chemistry - p-Block Elements",
        "Chemistry - d- and f-Block Elements",
        "Chemistry - Coordination Compounds",
        "Chemistry - Environmental Chemistry",
        "Chemistry - Purification and Characterisation of Organic Compounds",
        "Chemistry - Some Basic Principles of Organic Chemistry",
        "Chemistry - Hydrocarbons",
        "Chemistry - Organic Compounds Containing Halogens",
        "Chemistry - Organic Compounds Containing Oxygen",
        "Chemistry - Organic Compounds Containing Nitrogen",
        "Chemistry - Polymers",
        "Chemistry - Biomolecules",
        "Chemistry - Chemistry in Everyday Life",
        "Maths - Sets, Relations, and Functions",
        "Maths - Complex Numbers and Quadratic Equations",
        "Maths - Matrices and Determinants",
        "Maths - Permutations and Combinations",
        "Maths - Binomial Theorem and Its Simple Applications",
        "Maths - Sequence and Series",
        "Maths - Limit, Continuity and Differentiability",
        "Maths - Integral Calculus",
        "Maths - Differential Equations",
        "Maths - Co-ordinate Geometry",
        "Maths - Three Dimensional Geometry",
        "Maths - Vector Algebra",
        "Maths - Statistics and Probability",
        "Maths - Trigonometry",
        "Maths - Mathematical Reasoning",
    ],
    neet: [
        "Biology - Diversity in Living World",
        "Biology - Structural Organisation in Animals and Plants",
        "Biology - Cell Structure and Function",
        "Biology - Plant Physiology",
        "Biology - Human Physiology",
        "Biology - Reproduction",
        "Biology - Genetics and Evolution",
        "Biology - Biology and Human Welfare",
        "Biology - Biotechnology and Its Applications",
        "Biology - Ecology and Environment",
        "Physics - Physical World and Measurement",
        "Physics - Kinematics",
        "Physics - Laws of Motion",
        "Physics - Work, Energy, and Power",
        "Physics - Motion of System of Particles and Rigid Body",
        "Physics - Gravitation",
        "Physics - Properties of Bulk Matter",
        "Physics - Thermodynamics",
        "Physics - Behaviour of Perfect Gas and Kinetic Theory",
        "Physics - Oscillations and Waves",
        "Physics - Electrostatics",
        "Physics - Current Electricity",
        "Physics - Magnetic Effects of Current and Magnetism",
        "Physics - Electromagnetic Induction and Alternating Currents",
        "Physics - Electromagnetic Waves",
        "Physics - Optics",
        "Physics - Dual Nature of Matter and Radiation",
        "Physics - Atoms and Nuclei",
        "Physics - Electronic Devices",
        "Chemistry - Some Basic Concepts of Chemistry",
        "Chemistry - Structure of Atom",
        "Chemistry - Classification of Elements and Periodicity in Properties",
        "Chemistry - Chemical Bonding and Molecular Structure",
        "Chemistry - States of Matter: Gases and Liquids",
        "Chemistry - Thermodynamics",
        "Chemistry - Equilibrium",
        "Chemistry - Redox Reactions",
        "Chemistry - Hydrogen",
        "Chemistry - s-Block Element (Alkali and Alkaline earth metals)",
        "Chemistry - Some p-Block Elements",
        "Chemistry - Organic Chemistry- Some Basic Principles and Techniques",
        "Chemistry - Hydrocarbons",
        "Chemistry - Environmental Chemistry",
        "Chemistry - Solid State",
        "Chemistry - Solutions",
        "Chemistry - Electrochemistry",
        "Chemistry - Chemical Kinetics",
        "Chemistry - Surface Chemistry",
        "Chemistry - General Principles and Processes of Isolation of Elements",
        "Chemistry - p-Block Elements",
        "Chemistry - d and f Block Elements",
        "Chemistry - Coordination Compounds",
        "Chemistry - Haloalkanes and Haloarenes",
        "Chemistry - Alcohols, Phenols and Ethers",
        "Chemistry - Aldehydes, Ketones and Carboxylic Acids",
        "Chemistry - Organic Compounds Containing Nitrogen",
        "Chemistry - Biomolecules",
        "Chemistry - Polymers",
        "Chemistry - Chemistry in Everyday Life"
    ],
    upsc: [
        "History - Ancient India",
        "History - Medieval India",
        "History - Modern India",
        "History - World History",
        "Indian Heritage and Culture",
        "Geography - Physical Geography",
        "Geography - Indian Geography",
        "Geography - World Geography",
        "Polity - Indian Constitution",
        "Polity - Governance",
        "Polity - Social Justice",
        "Polity - International Relations",
        "Economy - Indian Economy",
        "Economy - Economic Development",
        "Environment and Ecology",
        "Science and Technology",
        "Current Affairs"
    ],
    cat: [
        "Quantitative Aptitude - Number System",
        "Quantitative Aptitude - Algebra",
        "Quantitative Aptitude - Geometry",
        "Quantitative Aptitude - Modern Math",
        "Quantitative Aptitude - Arithmetic",
        "Verbal Ability - Reading Comprehension",
        "Verbal Ability - Para-jumbles",
        "Verbal Ability - Para-summary",
        "Verbal Ability - Odd one out",
        "Verbal Ability - Grammar",
        "Data Interpretation - Tables",
        "Data Interpretation - Bar Graphs",
        "Data Interpretation - Line Charts",
        "Data Interpretation - Pie Charts",
        "Data Interpretation - Caselets",
        "Logical Reasoning - Seating Arrangement",
        "Logical Reasoning - Blood Relations",
        "Logical Reasoning - Syllogisms",
        "Logical Reasoning - Puzzles"
    ],
    gate: [
        "Computer Science - Engineering Mathematics",
        "Computer Science - Digital Logic",
        "Computer Science - Computer Organization and Architecture",
        "Computer Science - Programming and Data Structures",
        "Computer Science - Algorithms",
        "Computer Science - Theory of Computation",
        "Computer Science - Compiler Design",
        "Computer Science - Operating System",
        "Computer Science - Databases",
        "Computer Science - Computer Networks",
        "Mechanical - Engineering Mathematics",
        "Mechanical - Applied Mechanics and Design",
        "Mechanical - Fluid Mechanics and Thermal Sciences",
        "Mechanical - Materials, Manufacturing and Industrial Engineering",
        "Electronics - Engineering Mathematics",
        "Electronics - Networks, Signals and Systems",
        "Electronics - Electronic Devices",
        "Electronics - Analog Circuits",
        "Electronics - Digital Circuits",
        "Electronics - Control Systems",
        "Electronics - Communications",
        "Electronics - Electromagnetics",
        "Civil - Engineering Mathematics",
        "Civil - Structural Engineering",
        "Civil - Geotechnical Engineering",
        "Civil - Water Resources Engineering",
        "Civil - Environmental Engineering",
        "Civil - Transportation Engineering",
        "Civil - Geomatics Engineering"
    ],
}
