'use client';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';

const faqItems = [
    {
        question: "How does the AI Trainer work?",
        answer: "The AI Trainer uses a powerful language model to understand your questions and provide detailed, human-like answers. You can ask it anything from clarifying a concept to solving a complex problem. Just type your question and get an instant response!"
    },
    {
        question: "How are the mock tests generated?",
        answer: "Our mock tests are dynamically generated by an AI that understands the syllabus and question patterns for your selected exam. This ensures you get a unique and relevant set of questions every time you take a test."
    },
    {
        question: "Can I use the Image Solver for handwritten questions?",
        answer: "Yes! The Image Solver is designed to recognize both printed and clearly written handwritten questions. For best results, ensure the image is well-lit and the handwriting is legible."
    },
    {
        question: "How is my Study Roadmap personalized?",
        answer: "The study roadmap is generated based on the exam you select and your self-assessed knowledge level (Beginner, Intermediate, Advanced). The AI creates a structured plan with milestones and resources tailored to help you progress efficiently."
    },
    {
        question: "Is my performance data secure?",
        answer: "Absolutely. Your performance analytics data, such as mock test scores, is stored securely in your browser's local storage and is not shared with anyone. You can clear this data anytime from the Settings page."
    }
];

export function Help() {
  return (
    <div className="grid gap-6 max-w-4xl mx-auto">
        <Card>
            <CardHeader>
                <CardTitle>Frequently Asked Questions</CardTitle>
                <CardDescription>Find answers to common questions about PrepChamp.</CardDescription>
            </CardHeader>
            <CardContent>
                <Accordion type="single" collapsible className="w-full">
                    {faqItems.map((item, index) => (
                        <AccordionItem value={`item-${index}`} key={index}>
                            <AccordionTrigger>{item.question}</AccordionTrigger>
                            <AccordionContent>
                               {item.answer}
                            </AccordionContent>
                        </AccordionItem>
                    ))}
                </Accordion>
            </CardContent>
        </Card>
         <Card>
            <CardHeader>
                <CardTitle>Contact Us</CardTitle>
                <CardDescription>Still need help? Get in touch with our support team.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-2">
                <p className="text-sm">
                   For any issues or feedback, please email us at:
                </p>
                <a href="mailto:support@prepchamp.ai" className="text-primary font-medium">
                    support@prepchamp.ai
                </a>
            </CardContent>
        </Card>
    </div>
  );
}
